routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Auth\LoginController@showLoginForm');

Route::prefix('admin')->group(function ( ){
    Route::get('/', 'Auth\LoginController@showLoginForm');

    Route::get('/','Auth\LoginController@showLoginForm')->name('adminLogin');
    Route::get('/login','Auth\LoginController@showLoginForm')->name('adminLogin');
    Route::post('/login',[ 'as' => 'login', 'uses' => 'Auth\LoginController@login']);
    
    Route::middleware(['auth:web'])->group(function (){

        Route::get('logout', 'Auth\LoginController@logout')->name('AdminLogout');

        // product Crud
        Route::resource('product','ProductController');
        Route::post('product','ProductController@search')->name('product.search');
        Route::post('productstore','ProductController@store')->name('product.store');   
    });
});

resources/views/common/flash.blade.php
@if (count($errors) > 0)

        <div class="alert alert-danger alertdisapper">

            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    @if(session()->has('success'))

        <div class="alert alert-success alertdisapper">

            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

            {{ session()->get('success') }}

        </div>

    @endif


    @if(session()->has('error'))

        <div class="alert alert-danger alertdisapper">

            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

            {{ session()->get('error') }}

        </div>

    @endif


    <div id="error-message" style="display:none" class="alert alert-danger" data-dismiss="alert" aria-label="close">

        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

    </div>


    <div id="success-message" style="display:none" class="alert alert-success" data-dismiss="alert" aria-label="close">

        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>

    </div>

resources/views/common/footer.blade.php
<hr>
<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

@yield('js')
<script>
  $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
  });

  $(document).ready(function(){
        setTimeout(function(){$('.alertdisapper').fadeOut();}, 4000);
  });

  var url = $('meta[name="baseUrl"]').attr('content');

    $(document).on("click",'.btnDelete',function(event) {
      var url = $(this).data('url');
      event.preventDefault();
      if (confirm('Are you sure?')) {
              form = $('#deleteForm');
              form.attr('action', url);
              form.submit();
        }
    });

</script>

resources/views/common/forms.blade.php
<form id="deleteForm" name="deleteForm" action="" method="post">
    @csrf
    @method('DELETE')
</form>

resources/views/common/head.blade.php
<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="baseUrl" content="{{ url('/') }}">
    <title>@yield('title') | Admin {{ config('app.name') }}</title>
  
<!-- Bootstrap  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- sweetalert cdn -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js"></script>

<!-- Data Tables css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap4.min.css">

<!-- Datatables  script -->
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap4.min.js"></script>
    
<!-- lottiefiles  script -->
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

    @yield('css')
    
    <style>
        .row.content {height: 500px}
        footer { background-color: #555;color: white;padding: 15px; }
    </style>

resources/views/common/header.blade.php
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{{ route('product.index') }}">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="{{ request()->is('product*') ? 'active' : '' }}"><a href="{{ route('product.index') }}">Product</a></li>
        <li><a href="{{ route('product.index') }}">Product</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ route('AdminLogout') }}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>